services:
  - type: web
    name: malaria-deepl
    env: python
    buildCommand: bash build.sh
    startCommand: python -m gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

